/* =============================================================
   AUTO-GENERATED by scripts/update-teams.js
   Last run: 2026-05-17T06:28:27.387Z
   Sources:  football-data.org + api.clubelo.com + understat.com
   Schema v2: per-team atk_home/atk_away/def_home/def_away split
              + real xG when xg_source === "understat".
   DO NOT EDIT — this file is overwritten nightly.
   ============================================================= */

const LEAGUE_AVG = {
  "EPL": {
    "home": 1.529,
    "away": 1.227
  },
  "LALIGA": {
    "home": 1.561,
    "away": 1.131
  },
  "SERIEA": {
    "home": 1.286,
    "away": 1.133
  },
  "BUNDES": {
    "home": 1.778,
    "away": 1.458
  },
  "LIGUE1": {
    "home": 1.593,
    "away": 1.226
  },
  "NB1": {
    "home": 1.45,
    "away": 1.15
  },
  "UCL": {
    "home": 1.6,
    "away": 1.3
  },
  "OTHER": {
    "home": 1.5,
    "away": 1.2
  }
};

const TEAMS = {
  "1. FC Köln": {"elo":1600,"league":"BUNDES","atk_home":0.963,"atk_away":0.774,"def_home":1.249,"def_away":1.148,"atk":0.869,"def":1.198,"form":-0.072,"xg_for":1.42,"xg_ag":1.93,"xg_source":"proxy","inj":0.05},
  "AC Milan": {"elo":1757,"league":"SERIEA","atk_home":1.002,"atk_away":1.199,"def_home":0.988,"def_away":0.588,"atk":1.101,"def":0.788,"form":-0.048,"xg_for":1.32,"xg_ag":0.94,"xg_source":"proxy","inj":0.05},
  "Alaves": {"elo":1637,"league":"LALIGA","atk_home":0.87,"atk_away":1.005,"def_home":1.19,"def_away":1.168,"atk":0.937,"def":1.179,"form":0,"xg_for":1.25,"xg_ag":1.58,"xg_source":"proxy","inj":0.05},
  "Angers": {"elo":1543,"league":"LIGUE1","atk_home":0.616,"atk_away":0.532,"def_home":1.002,"def_away":1.114,"atk":0.574,"def":1.058,"form":-0.072,"xg_for":0.82,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Arsenal": {"elo":2060,"league":"EPL","atk_home":1.405,"atk_away":1.296,"def_home":0.52,"def_away":0.554,"atk":1.35,"def":0.537,"form":0.024,"xg_for":1.87,"xg_ag":0.74,"xg_source":"proxy","inj":0.05},
  "Aston Villa": {"elo":1889,"league":"EPL","atk_home":1.159,"atk_away":0.994,"def_home":1.025,"def_away":0.972,"atk":1.076,"def":0.999,"form":0,"xg_for":1.5,"xg_ag":1.37,"xg_source":"proxy","inj":0.05},
  "Atalanta": {"elo":1777,"league":"SERIEA","atk_home":1.049,"atk_away":1.289,"def_home":0.659,"def_away":0.894,"atk":1.169,"def":0.776,"form":-0.024,"xg_for":1.4,"xg_ag":0.95,"xg_source":"proxy","inj":0.05},
  "Athletic Bilbao": {"elo":1684,"league":"LALIGA","atk_home":0.738,"atk_away":0.986,"def_home":0.987,"def_away":1.217,"atk":0.862,"def":1.102,"form":-0.024,"xg_for":1.13,"xg_ag":1.51,"xg_source":"proxy","inj":0.05},
  "Atletico Madrid": {"elo":1844,"league":"LALIGA","atk_home":1.296,"atk_away":1.129,"def_home":0.884,"def_away":0.814,"atk":1.213,"def":0.849,"form":0.024,"xg_for":1.65,"xg_ag":1.13,"xg_source":"proxy","inj":0.05},
  "Auxerre": {"elo":1604,"league":"LIGUE1","atk_home":0.706,"atk_away":0.794,"def_home":0.789,"def_away":1.039,"atk":0.75,"def":0.914,"form":0.024,"xg_for":1.05,"xg_ag":1.31,"xg_source":"proxy","inj":0.05},
  "Barcelona": {"elo":1969,"league":"LALIGA","atk_home":1.88,"atk_away":1.72,"def_home":0.435,"def_away":0.761,"atk":1.8,"def":0.598,"form":0.072,"xg_for":2.44,"xg_ag":0.84,"xg_source":"proxy","inj":0.05},
  "Bayer Leverkusen": {"elo":1813,"league":"BUNDES","atk_home":1.279,"atk_away":1.17,"def_home":0.806,"def_away":0.9,"atk":1.224,"def":0.853,"form":0,"xg_for":1.99,"xg_ag":1.39,"xg_source":"proxy","inj":0.05},
  "Bayern Munich": {"elo":2002,"league":"BUNDES","atk_home":2.235,"atk_away":2.149,"def_home":0.845,"def_away":0.579,"atk":2.192,"def":0.712,"form":0.096,"xg_for":3.55,"xg_ag":1.13,"xg_source":"proxy","inj":0.05},
  "Bologna": {"elo":1686,"league":"SERIEA","atk_home":0.617,"atk_away":1.441,"def_home":1.018,"def_away":1.011,"atk":1.029,"def":1.014,"form":0,"xg_for":1.21,"xg_ag":1.23,"xg_source":"proxy","inj":0.05},
  "Borussia Dortmund": {"elo":1831,"league":"BUNDES","atk_home":1.361,"atk_away":1.182,"def_home":0.689,"def_away":0.58,"atk":1.272,"def":0.634,"form":0.024,"xg_for":2.07,"xg_ag":1.02,"xg_source":"proxy","inj":0.05},
  "Borussia Monchengladbach": {"elo":1625,"league":"BUNDES","atk_home":0.852,"atk_away":0.694,"def_home":0.847,"def_away":1.005,"atk":0.773,"def":0.926,"form":0.024,"xg_for":1.26,"xg_ag":1.51,"xg_source":"proxy","inj":0.05},
  "Bournemouth": {"elo":1867,"league":"EPL","atk_home":1.048,"atk_away":1.236,"def_home":0.898,"def_away":1.065,"atk":1.142,"def":0.982,"form":0.096,"xg_for":1.56,"xg_ag":1.37,"xg_source":"proxy","inj":0.05},
  "Brentford": {"elo":1833,"league":"EPL","atk_home":1.101,"atk_away":0.946,"def_home":0.854,"def_away":1.071,"atk":1.023,"def":0.962,"form":-0.024,"xg_for":1.42,"xg_ag":1.34,"xg_source":"proxy","inj":0.05},
  "Brest": {"elo":1623,"league":"LIGUE1","atk_home":1.086,"atk_away":0.659,"def_home":1.163,"def_away":1.178,"atk":0.872,"def":1.171,"form":-0.072,"xg_for":1.27,"xg_ag":1.65,"xg_source":"proxy","inj":0.05},
  "Brighton": {"elo":1861,"league":"EPL","atk_home":1.103,"atk_away":1.017,"def_home":0.717,"def_away":0.89,"atk":1.06,"def":0.804,"form":0.048,"xg_for":1.47,"xg_ag":1.12,"xg_source":"proxy","inj":0.05},
  "Burnley": {"elo":1665,"league":"EPL","atk_home":0.615,"atk_away":0.881,"def_home":1.326,"def_away":1.624,"atk":0.748,"def":1.475,"form":-0.096,"xg_for":1.01,"xg_ag":2.06,"xg_source":"proxy","inj":0.05},
  "Cagliari": {"elo":1573,"league":"SERIEA","atk_home":0.86,"atk_away":0.751,"def_home":1.074,"def_away":1.286,"atk":0.805,"def":1.18,"form":0,"xg_for":0.98,"xg_ag":1.44,"xg_source":"proxy","inj":0.05},
  "Celta Vigo": {"elo":1696,"league":"LALIGA","atk_home":1.067,"atk_away":1.114,"def_home":1.463,"def_away":0.682,"atk":1.091,"def":1.072,"form":-0.024,"xg_for":1.46,"xg_ag":1.36,"xg_source":"proxy","inj":0.05},
  "Chelsea": {"elo":1833,"league":"EPL","atk_home":0.827,"atk_away":1.32,"def_home":1.169,"def_away":0.954,"atk":1.073,"def":1.061,"form":-0.096,"xg_for":1.44,"xg_ag":1.45,"xg_source":"proxy","inj":0.05},
  "Como": {"elo":1749,"league":"SERIEA","atk_home":1.513,"atk_away":1.289,"def_home":0.795,"def_away":0.532,"atk":1.401,"def":0.664,"form":0,"xg_for":1.7,"xg_ag":0.79,"xg_source":"proxy","inj":0.05},
  "Crystal Palace": {"elo":1796,"league":"EPL","atk_home":0.653,"atk_away":0.856,"def_home":0.951,"def_away":1.056,"atk":0.755,"def":1.004,"form":-0.072,"xg_for":1.02,"xg_ag":1.39,"xg_source":"proxy","inj":0.05},
  "Debrecen": {"league":"NB1","elo":1540,"atk":0.95,"def":1.05,"form":-0.01,"xg_for":1.2,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Diosgyor": {"league":"NB1","elo":1510,"atk":0.85,"def":1.1,"form":-0.03,"xg_for":1.05,"xg_ag":1.45,"inj":0.06,"xg_source":"manual"},
  "Eintracht Frankfurt": {"elo":1664,"league":"BUNDES","atk_home":0.932,"atk_away":1.213,"def_home":1.101,"def_away":1.212,"atk":1.073,"def":1.156,"form":-0.072,"xg_for":1.71,"xg_ag":1.88,"xg_source":"proxy","inj":0.05},
  "Elche": {"elo":1615,"league":"LALIGA","atk_home":1.043,"atk_away":0.892,"def_home":0.988,"def_away":1.341,"atk":0.967,"def":1.164,"form":0,"xg_for":1.32,"xg_ag":1.6,"xg_source":"proxy","inj":0.05},
  "Espanyol": {"elo":1621,"league":"LALIGA","atk_home":0.662,"atk_away":0.962,"def_home":1.115,"def_away":1.13,"atk":0.812,"def":1.122,"form":-0.048,"xg_for":1.06,"xg_ag":1.51,"xg_source":"proxy","inj":0.05},
  "Everton": {"elo":1826,"league":"EPL","atk_home":0.947,"atk_away":0.995,"def_home":1.137,"def_away":0.831,"atk":0.971,"def":0.984,"form":-0.048,"xg_for":1.33,"xg_ag":1.33,"xg_source":"proxy","inj":0.05},
  "FC Augsburg": {"elo":1655,"league":"BUNDES","atk_home":0.863,"atk_away":0.804,"def_home":1.077,"def_away":1.1,"atk":0.834,"def":1.088,"form":0.048,"xg_for":1.35,"xg_ag":1.76,"xg_source":"proxy","inj":0.05},
  "FC Heidenheim": {"elo":1564,"league":"BUNDES","atk_home":0.799,"atk_away":0.81,"def_home":1.479,"def_away":1.13,"atk":0.804,"def":1.305,"form":0,"xg_for":1.3,"xg_ag":2.08,"xg_source":"proxy","inj":0.05},
  "Ferencvaros": {"league":"NB1","elo":1720,"atk":1.4,"def":0.85,"form":0.05,"xg_for":1.9,"xg_ag":1,"inj":0.05,"xg_source":"manual"},
  "Fiorentina": {"elo":1650,"league":"SERIEA","atk_home":0.813,"atk_away":0.931,"def_home":0.847,"def_away":1.293,"atk":0.872,"def":1.07,"form":0,"xg_for":1.05,"xg_ag":1.31,"xg_source":"proxy","inj":0.05},
  "Fulham": {"elo":1801,"league":"EPL","atk_home":0.985,"atk_away":0.685,"def_home":0.9,"def_away":1.063,"atk":0.835,"def":0.981,"form":-0.048,"xg_for":1.17,"xg_ag":1.36,"xg_source":"proxy","inj":0.05},
  "Genoa": {"elo":1633,"league":"SERIEA","atk_home":0.976,"atk_away":0.865,"def_home":1.197,"def_away":0.958,"atk":0.921,"def":1.078,"form":0.024,"xg_for":1.12,"xg_ag":1.29,"xg_source":"proxy","inj":0.05},
  "Getafe": {"elo":1667,"league":"LALIGA","atk_home":0.62,"atk_away":0.666,"def_home":0.82,"def_away":0.668,"atk":0.643,"def":0.744,"form":0,"xg_for":0.86,"xg_ag":0.98,"xg_source":"proxy","inj":0.05},
  "Girona": {"elo":1642,"league":"LALIGA","atk_home":0.739,"atk_away":0.894,"def_home":1.198,"def_away":0.905,"atk":0.817,"def":1.052,"form":-0.072,"xg_for":1.08,"xg_ag":1.38,"xg_source":"proxy","inj":0.05},
  "Gyor": {"league":"NB1","elo":1540,"atk":0.95,"def":1.05,"form":0,"xg_for":1.2,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Hamburger SV": {"elo":1598,"league":"BUNDES","atk_home":0.827,"atk_away":0.67,"def_home":0.922,"def_away":1.052,"atk":0.749,"def":0.987,"form":0,"xg_for":1.22,"xg_ag":1.61,"xg_source":"proxy","inj":0.05},
  "Hellas Verona": {"elo":1498,"league":"SERIEA","atk_home":0.46,"atk_away":0.617,"def_home":1.254,"def_away":1.366,"atk":0.538,"def":1.31,"form":-0.072,"xg_for":0.65,"xg_ag":1.59,"xg_source":"proxy","inj":0.05},
  "Hoffenheim": {"elo":1720,"league":"BUNDES","atk_home":1.151,"atk_away":1.16,"def_home":0.808,"def_away":1.114,"atk":1.155,"def":0.961,"form":0.048,"xg_for":1.87,"xg_ag":1.58,"xg_source":"proxy","inj":0.05},
  "Inter": {"elo":1901,"league":"SERIEA","atk_home":2.121,"atk_away":1.806,"def_home":0.734,"def_away":0.677,"atk":1.964,"def":0.705,"form":0.096,"xg_for":2.39,"xg_ag":0.85,"xg_source":"proxy","inj":0.05},
  "Juventus": {"elo":1794,"league":"SERIEA","atk_home":1.506,"atk_away":1.195,"def_home":0.663,"def_away":0.664,"atk":1.351,"def":0.663,"form":0.072,"xg_for":1.65,"xg_ag":0.8,"xg_source":"proxy","inj":0.05},
  "Kecskemet": {"league":"NB1","elo":1520,"atk":0.9,"def":1.05,"form":-0.01,"xg_for":1.15,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Lazio": {"elo":1708,"league":"SERIEA","atk_home":1.037,"atk_away":0.746,"def_home":1.272,"def_away":0.551,"atk":0.892,"def":0.911,"form":0,"xg_for":1.09,"xg_ag":1.07,"xg_source":"proxy","inj":0.05},
  "Le Havre": {"elo":1563,"league":"LIGUE1","atk_home":0.731,"atk_away":0.54,"def_home":0.892,"def_away":0.996,"atk":0.635,"def":0.944,"form":-0.024,"xg_for":0.91,"xg_ag":1.34,"xg_source":"proxy","inj":0.05},
  "Lecce": {"elo":1547,"league":"SERIEA","atk_home":0.514,"atk_away":0.587,"def_home":1.189,"def_away":1.015,"atk":0.551,"def":1.102,"form":-0.024,"xg_for":0.66,"xg_ag":1.33,"xg_source":"proxy","inj":0.05},
  "Leeds United": {"elo":1801,"league":"EPL","atk_home":1.035,"atk_away":0.949,"def_home":0.927,"def_away":1.083,"atk":0.992,"def":1.005,"form":0.072,"xg_for":1.37,"xg_ag":1.4,"xg_source":"proxy","inj":0.05},
  "Levante UD": {"elo":1635,"league":"LALIGA","atk_home":0.901,"atk_away":0.962,"def_home":1.235,"def_away":1.177,"atk":0.932,"def":1.206,"form":0.048,"xg_for":1.25,"xg_ag":1.62,"xg_source":"proxy","inj":0.05},
  "Lille OSC": {"elo":1600,"league":"LIGUE1","atk_home":0.899,"atk_away":1.28,"def_home":0.755,"def_away":0.636,"atk":1.09,"def":0.696,"form":0.072,"xg_for":1.5,"xg_ag":0.97,"xg_source":"proxy","inj":0.05},
  "Liverpool": {"elo":1923,"league":"EPL","atk_home":1.216,"atk_away":1.249,"def_home":0.847,"def_away":1.169,"atk":1.232,"def":1.008,"form":0,"xg_for":1.7,"xg_ag":1.41,"xg_source":"proxy","inj":0.05},
  "Lorient": {"elo":1654,"league":"LIGUE1","atk_home":1.185,"atk_away":0.95,"def_home":1.099,"def_away":0.92,"atk":1.068,"def":1.009,"form":0,"xg_for":1.53,"xg_ag":1.41,"xg_source":"proxy","inj":0.05},
  "Lyon": {"elo":1749,"league":"LIGUE1","atk_home":1.223,"atk_away":1.103,"def_home":0.768,"def_away":0.813,"atk":1.163,"def":0.791,"form":0.072,"xg_for":1.65,"xg_ag":1.12,"xg_source":"proxy","inj":0.05},
  "Mainz": {"elo":1664,"league":"BUNDES","atk_home":0.747,"atk_away":0.955,"def_home":1.053,"def_away":0.859,"atk":0.851,"def":0.956,"form":0,"xg_for":1.36,"xg_ag":1.53,"xg_source":"proxy","inj":0.05},
  "Mallorca": {"elo":1646,"league":"LALIGA","atk_home":1.04,"atk_away":0.773,"def_home":1.002,"def_away":1.213,"atk":0.907,"def":1.107,"form":-0.024,"xg_for":1.25,"xg_ag":1.51,"xg_source":"proxy","inj":0.05},
  "Manchester City": {"elo":1600,"league":"EPL","atk_home":1.599,"atk_away":1.415,"def_home":0.521,"def_away":0.727,"atk":1.507,"def":0.624,"form":0.096,"xg_for":2.09,"xg_ag":0.88,"xg_source":"proxy","inj":0.05},
  "Manchester United": {"elo":1600,"league":"EPL","atk_home":1.331,"atk_away":1.193,"def_home":1.008,"def_away":0.875,"atk":1.262,"def":0.941,"form":0.048,"xg_for":1.75,"xg_ag":1.29,"xg_source":"proxy","inj":0.05},
  "Marseille": {"elo":1706,"league":"LIGUE1","atk_home":1.392,"atk_away":0.989,"def_home":0.984,"def_away":0.981,"atk":1.191,"def":0.983,"form":0,"xg_for":1.71,"xg_ag":1.38,"xg_source":"proxy","inj":0.05},
  "Metz": {"elo":1485,"league":"LIGUE1","atk_home":0.557,"atk_away":0.875,"def_home":1.656,"def_away":1.669,"atk":0.716,"def":1.663,"form":-0.096,"xg_for":0.98,"xg_ag":2.34,"xg_source":"proxy","inj":0.05},
  "Monaco": {"elo":1724,"league":"LIGUE1","atk_home":1.17,"atk_away":1.218,"def_home":1.053,"def_away":1.016,"atk":1.194,"def":1.034,"form":-0.024,"xg_for":1.68,"xg_ag":1.45,"xg_source":"proxy","inj":0.05},
  "MTK": {"league":"NB1","elo":1540,"atk":1,"def":1.05,"form":0,"xg_for":1.25,"xg_ag":1.35,"inj":0.05,"xg_source":"manual"},
  "Nantes": {"elo":1542,"league":"LIGUE1","atk_home":0.748,"atk_away":0.485,"def_home":1.329,"def_away":0.928,"atk":0.616,"def":1.129,"form":-0.048,"xg_for":0.89,"xg_ag":1.55,"xg_source":"proxy","inj":0.05},
  "Napoli": {"elo":1772,"league":"SERIEA","atk_home":1.379,"atk_away":1.051,"def_home":0.924,"def_away":0.776,"atk":1.215,"def":0.85,"form":-0.024,"xg_for":1.48,"xg_ag":1.02,"xg_source":"proxy","inj":0.05},
  "Newcastle": {"elo":1839,"league":"EPL","atk_home":1.207,"atk_away":0.786,"def_home":1.349,"def_away":0.854,"atk":0.997,"def":1.101,"form":-0.048,"xg_for":1.41,"xg_ag":1.48,"xg_source":"proxy","inj":0.05},
  "Nice": {"elo":1585,"league":"LIGUE1","atk_home":0.707,"atk_away":0.841,"def_home":1.46,"def_away":1.149,"atk":0.774,"def":1.305,"form":-0.024,"xg_for":1.08,"xg_ag":1.81,"xg_source":"proxy","inj":0.05},
  "Nottingham Forest": {"elo":1824,"league":"EPL","atk_home":0.696,"atk_away":1.35,"def_home":0.918,"def_away":0.869,"atk":1.023,"def":0.894,"form":0.072,"xg_for":1.36,"xg_ag":1.23,"xg_source":"proxy","inj":0.05},
  "Nyiregyhaza": {"league":"NB1","elo":1500,"atk":0.85,"def":1.15,"form":-0.04,"xg_for":1,"xg_ag":1.55,"inj":0.06,"xg_source":"manual"},
  "Osasuna": {"elo":1670,"league":"LALIGA","atk_home":1.05,"atk_away":0.722,"def_home":1.123,"def_away":0.927,"atk":0.886,"def":1.025,"form":-0.072,"xg_for":1.23,"xg_ag":1.36,"xg_source":"proxy","inj":0.05},
  "Paks": {"league":"NB1","elo":1600,"atk":1.15,"def":0.95,"form":0.02,"xg_for":1.5,"xg_ag":1.15,"inj":0.05,"xg_source":"manual"},
  "Paris": {"elo":1613,"league":"LIGUE1","atk_home":1.051,"atk_away":0.917,"def_home":1.26,"def_away":0.793,"atk":0.984,"def":1.026,"form":0.024,"xg_for":1.4,"xg_ag":1.4,"xg_source":"proxy","inj":0.05},
  "Paris Saint-Germain": {"elo":1600,"league":"LIGUE1","atk_home":1.504,"atk_away":1.651,"def_home":0.629,"def_away":0.531,"atk":1.578,"def":0.58,"form":0.096,"xg_for":2.21,"xg_ag":0.81,"xg_source":"proxy","inj":0.05},
  "Parma": {"elo":1595,"league":"SERIEA","atk_home":0.671,"atk_away":0.608,"def_home":1.248,"def_away":0.87,"atk":0.639,"def":1.059,"form":0,"xg_for":0.78,"xg_ag":1.27,"xg_source":"proxy","inj":0.05},
  "Pisa": {"elo":1463,"league":"SERIEA","atk_home":0.453,"atk_away":0.677,"def_home":1.211,"def_away":1.894,"atk":0.565,"def":1.553,"form":-0.12,"xg_for":0.67,"xg_ag":1.9,"xg_source":"proxy","inj":0.05},
  "Puskas Akademia": {"league":"NB1","elo":1620,"atk":1.2,"def":0.95,"form":0.03,"xg_for":1.55,"xg_ag":1.15,"inj":0.05,"xg_source":"manual"},
  "Racing Club de Lens": {"elo":1600,"league":"LIGUE1","atk_home":1.291,"atk_away":1.398,"def_home":0.675,"def_away":0.917,"atk":1.344,"def":0.796,"form":0.024,"xg_for":1.88,"xg_ag":1.14,"xg_source":"proxy","inj":0.05},
  "Rayo Vallecano": {"elo":1696,"league":"LALIGA","atk_home":0.84,"atk_away":0.709,"def_home":0.759,"def_away":0.981,"atk":0.775,"def":0.87,"form":0.048,"xg_for":1.06,"xg_ag":1.2,"xg_source":"proxy","inj":0.05},
  "RB Leipzig": {"elo":1778,"league":"BUNDES","atk_home":1.312,"atk_away":1.064,"def_home":0.814,"def_away":0.927,"atk":1.188,"def":0.871,"form":0.024,"xg_for":1.94,"xg_ag":1.42,"xg_source":"proxy","inj":0.05},
  "Real Betis": {"elo":1748,"league":"LALIGA","atk_home":1.127,"atk_away":1.193,"def_home":0.854,"def_away":0.953,"atk":1.16,"def":0.904,"form":0.072,"xg_for":1.55,"xg_ag":1.23,"xg_source":"proxy","inj":0.05},
  "Real Madrid": {"elo":1919,"league":"LALIGA","atk_home":1.461,"atk_away":1.424,"def_home":0.717,"def_away":0.674,"atk":1.443,"def":0.695,"form":0.048,"xg_for":1.95,"xg_ag":0.93,"xg_source":"proxy","inj":0.05},
  "Real Oviedo": {"elo":1600,"league":"LALIGA","atk_home":0.347,"atk_away":0.871,"def_home":0.767,"def_away":1.415,"atk":0.609,"def":1.091,"form":-0.072,"xg_for":0.76,"xg_ag":1.54,"xg_source":"proxy","inj":0.05},
  "Real Sociedad": {"elo":1680,"league":"LALIGA","atk_home":1.248,"atk_away":1.065,"def_home":1.332,"def_away":1.063,"atk":1.156,"def":1.198,"form":-0.048,"xg_for":1.58,"xg_ag":1.58,"xg_source":"proxy","inj":0.05},
  "Rennes": {"elo":1725,"league":"LIGUE1","atk_home":1.081,"atk_away":1.565,"def_home":0.819,"def_away":1.174,"atk":1.323,"def":0.996,"form":0.072,"xg_for":1.82,"xg_ag":1.44,"xg_source":"proxy","inj":0.05},
  "Roma": {"elo":1782,"league":"SERIEA","atk_home":1.445,"atk_away":1.241,"def_home":0.49,"def_away":1.013,"atk":1.343,"def":0.751,"form":0.096,"xg_for":1.63,"xg_ag":0.93,"xg_source":"proxy","inj":0.05},
  "SC Freiburg": {"elo":1720,"league":"BUNDES","atk_home":1.104,"atk_away":0.715,"def_home":0.883,"def_away":1.176,"atk":0.91,"def":1.029,"form":0,"xg_for":1.5,"xg_ag":1.69,"xg_source":"proxy","inj":0.05},
  "Sevilla": {"elo":1636,"league":"LALIGA","atk_home":0.832,"atk_away":1.076,"def_home":1.108,"def_away":1.255,"atk":0.954,"def":1.181,"form":0.024,"xg_for":1.26,"xg_ag":1.61,"xg_source":"proxy","inj":0.05},
  "St. Pauli": {"elo":1547,"league":"BUNDES","atk_home":0.536,"atk_away":0.478,"def_home":1.252,"def_away":0.982,"atk":0.507,"def":1.117,"form":-0.096,"xg_for":0.83,"xg_ag":1.79,"xg_source":"proxy","inj":0.05},
  "Strasbourg": {"elo":1702,"league":"LIGUE1","atk_home":0.937,"atk_away":1.371,"def_home":0.862,"def_away":0.989,"atk":1.154,"def":0.926,"form":0,"xg_for":1.59,"xg_ag":1.32,"xg_source":"proxy","inj":0.05},
  "Sunderland": {"elo":1706,"league":"EPL","atk_home":0.742,"atk_away":0.715,"def_home":0.921,"def_away":1.023,"atk":0.729,"def":0.972,"form":-0.024,"xg_for":1.01,"xg_ag":1.35,"xg_source":"proxy","inj":0.05},
  "Torino": {"elo":1629,"league":"SERIEA","atk_home":1.164,"atk_away":0.763,"def_home":1.292,"def_away":1.36,"atk":0.963,"def":1.326,"form":0.024,"xg_for":1.18,"xg_ag":1.61,"xg_source":"proxy","inj":0.05},
  "Tottenham": {"elo":1772,"league":"EPL","atk_home":0.754,"atk_away":1.05,"def_home":1.49,"def_away":0.869,"atk":0.902,"def":1.18,"form":0.024,"xg_for":1.22,"xg_ag":1.58,"xg_source":"proxy","inj":0.05},
  "Toulouse": {"elo":1653,"league":"LIGUE1","atk_home":0.87,"atk_away":1.182,"def_home":1.139,"def_away":0.934,"atk":1.026,"def":1.037,"form":0,"xg_for":1.42,"xg_ag":1.44,"xg_source":"proxy","inj":0.05},
  "Udinese": {"elo":1663,"league":"SERIEA","atk_home":0.772,"atk_away":1.414,"def_home":0.897,"def_away":1.084,"atk":1.093,"def":0.991,"form":0.048,"xg_for":1.3,"xg_ag":1.21,"xg_source":"proxy","inj":0.05},
  "Ujpest": {"league":"NB1","elo":1550,"atk":0.95,"def":1,"form":0,"xg_for":1.2,"xg_ag":1.3,"inj":0.05,"xg_source":"manual"},
  "Union Berlin": {"elo":1605,"league":"BUNDES","atk_home":0.881,"atk_away":0.746,"def_home":1.047,"def_away":1.066,"atk":0.813,"def":1.056,"form":0,"xg_for":1.33,"xg_ag":1.71,"xg_source":"proxy","inj":0.05},
  "US Cremonese": {"elo":1600,"league":"SERIEA","atk_home":0.723,"atk_away":0.593,"def_home":1.225,"def_away":1.275,"atk":0.658,"def":1.25,"form":-0.048,"xg_for":0.8,"xg_ag":1.51,"xg_source":"proxy","inj":0.05},
  "US Sassuolo Calcio": {"elo":1600,"league":"SERIEA","atk_home":1.032,"atk_away":0.992,"def_home":1.098,"def_away":0.996,"atk":1.012,"def":1.047,"form":0,"xg_for":1.23,"xg_ag":1.26,"xg_source":"proxy","inj":0.05},
  "Valencia": {"elo":1670,"league":"LALIGA","atk_home":0.849,"atk_away":0.767,"def_home":1.15,"def_away":0.92,"atk":0.808,"def":1.035,"form":0.024,"xg_for":1.1,"xg_ag":1.37,"xg_source":"proxy","inj":0.05},
  "VfB Stuttgart": {"elo":1767,"league":"BUNDES","atk_home":1.029,"atk_away":1.716,"def_home":0.643,"def_away":1.137,"atk":1.372,"def":0.89,"form":0,"xg_for":2.17,"xg_ag":1.48,"xg_source":"proxy","inj":0.05},
  "Villarreal": {"elo":1755,"league":"LALIGA","atk_home":1.549,"atk_away":1.146,"def_home":0.979,"def_away":0.884,"atk":1.347,"def":0.931,"form":0.024,"xg_for":1.86,"xg_ag":1.24,"xg_source":"proxy","inj":0.05},
  "Werder Bremen": {"elo":1600,"league":"BUNDES","atk_home":0.613,"atk_away":0.696,"def_home":1.266,"def_away":0.907,"atk":0.654,"def":1.086,"form":-0.048,"xg_for":1.05,"xg_ag":1.73,"xg_source":"proxy","inj":0.05},
  "West Ham": {"elo":1758,"league":"EPL","atk_home":0.899,"atk_away":0.78,"def_home":1.208,"def_away":1.174,"atk":0.839,"def":1.191,"form":0,"xg_for":1.17,"xg_ag":1.64,"xg_source":"proxy","inj":0.05},
  "Wolfsburg": {"elo":1590,"league":"BUNDES","atk_home":0.644,"atk_away":1.004,"def_home":1.229,"def_away":1.254,"atk":0.824,"def":1.242,"form":0.024,"xg_for":1.3,"xg_ag":2.01,"xg_source":"proxy","inj":0.05},
  "Wolves": {"elo":1674,"league":"EPL","atk_home":0.657,"atk_away":0.32,"def_home":1.373,"def_away":1.262,"atk":0.489,"def":1.318,"form":-0.096,"xg_for":0.7,"xg_ag":1.81,"xg_source":"proxy","inj":0.05},
  "ZTE": {"league":"NB1","elo":1530,"atk":0.9,"def":1.08,"form":-0.02,"xg_for":1.15,"xg_ag":1.45,"inj":0.05,"xg_source":"manual"},
};

const TEAM_ALIASES = {
  "Man City": "Manchester City",
  "Man Utd": "Manchester United",
  "MU": "Manchester United",
  "Spurs": "Tottenham",
  "Nott'm Forest": "Nottingham Forest",
  "Atleti": "Atletico Madrid",
  "Atletico": "Atletico Madrid",
  "Real": "Real Madrid",
  "Barca": "Barcelona",
  "BVB": "Borussia Dortmund",
  "Gladbach": "Borussia Monchengladbach",
  "Bayern": "Bayern Munich",
  "Leverkusen": "Bayer Leverkusen",
  "PSG": "Paris Saint-Germain",
  "Fradi": "Ferencvaros",
  "FTC": "Ferencvaros"
};
