/* =============================================================
   AUTO-GENERATED by scripts/update-teams.js
   Last run: 2026-08-31T09:35:50.047Z
   Sources:  football-data.org + api.clubelo.com + understat.com
   Schema v2: per-team atk_home/atk_away/def_home/def_away split
              + real xG when xg_source === "understat".
   DO NOT EDIT — this file is overwritten nightly.
   ============================================================= */

const LEAGUE_AVG = {
  "EPL": {
    "home": 1.947,
    "away": 1.263
  },
  "LALIGA": {
    "home": 1.692,
    "away": 1.154
  },
  "SERIEA": {
    "home": 1.313,
    "away": 1.313
  },
  "BUNDES": {
    "home": 2.889,
    "away": 1
  },
  "LIGUE1": {
    "home": 1.647,
    "away": 1.412
  },
  "NB1": {
    "home": 1.45,
    "away": 1.15
  },
  "UCL": {
    "home": 1.6,
    "away": 1.3
  },
  "OTHER": {
    "home": 1.5,
    "away": 1.2
  }
};

const TEAMS = {
  "AC Milan": {"elo":1750,"league":"SERIEA","atk_home":1.524,"atk_away":1.524,"def_home":0,"def_away":0.762,"atk":1.524,"def":0.381,"form":0.12,"xg_for":2,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Alaves": {"elo":1635,"league":"LALIGA","atk_home":1.17,"atk_away":0.867,"def_home":0,"def_away":0.591,"atk":1.018,"def":0.295,"form":0.08,"xg_for":1.49,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Angers": {"elo":1548,"league":"LIGUE1","atk_home":0,"atk_away":2.125,"def_home":1.417,"def_away":0.607,"atk":1.063,"def":1.012,"form":0,"xg_for":1.5,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Athletic Bilbao": {"elo":1678,"league":"LALIGA","atk_home":0.591,"atk_away":0,"def_home":2.6,"def_away":1.182,"atk":0.295,"def":1.891,"form":-0.12,"xg_for":0.5,"xg_ag":2.5,"xg_source":"proxy","inj":0.05},
  "Atletico Madrid": {"elo":1828,"league":"LALIGA","atk_home":1.182,"atk_away":2.6,"def_home":0.872,"def_away":0.591,"atk":1.891,"def":0.731,"form":0.08,"xg_for":2.5,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Auxerre": {"elo":1624,"league":"LIGUE1","atk_home":0.607,"atk_away":1.417,"def_home":2.125,"def_away":3.036,"atk":1.012,"def":2.58,"form":-0.12,"xg_for":1.5,"xg_ag":4,"xg_source":"proxy","inj":0.05},
  "Barcelona": {"elo":1952,"league":"LALIGA","atk_home":1.182,"atk_away":4.333,"def_home":0,"def_away":0,"atk":2.758,"def":0,"form":0.12,"xg_for":3.5,"xg_ag":0,"xg_source":"proxy","inj":0.05},
  "Bournemouth": {"elo":1872,"league":"EPL","atk_home":0.514,"atk_away":0.792,"def_home":0.792,"def_away":1.027,"atk":0.653,"def":0.909,"form":-0.06,"xg_for":1,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Brentford": {"elo":1837,"league":"EPL","atk_home":1.541,"atk_away":0.792,"def_home":0,"def_away":0.514,"atk":1.166,"def":0.257,"form":0.06,"xg_for":2,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Brest": {"elo":1621,"league":"LIGUE1","atk_home":1.214,"atk_away":1.417,"def_home":1.417,"def_away":1.214,"atk":1.315,"def":1.315,"form":0,"xg_for":2,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Brighton": {"elo":1842,"league":"EPL","atk_home":2.054,"atk_away":2.375,"def_home":0,"def_away":2.054,"atk":2.215,"def":1.027,"form":0,"xg_for":3.5,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Celta Vigo": {"elo":1701,"league":"LALIGA","atk_home":0.591,"atk_away":0,"def_home":1.733,"def_away":0,"atk":0.295,"def":0.867,"form":-0.06,"xg_for":0.5,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Chelsea": {"elo":1831,"league":"EPL","atk_home":2.054,"atk_away":2.375,"def_home":2.375,"def_away":1.027,"atk":2.215,"def":1.701,"form":0.12,"xg_for":3.5,"xg_ag":2.5,"xg_source":"proxy","inj":0.05},
  "Coventry City": {"elo":1600,"league":"EPL","atk_home":0,"atk_away":0,"def_home":0.792,"def_away":1.541,"atk":0,"def":1.166,"form":-0.12,"xg_for":0,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Crystal Palace": {"elo":1804,"league":"EPL","atk_home":0.514,"atk_away":0,"def_home":3.167,"def_away":1.027,"atk":0.257,"def":2.097,"form":-0.12,"xg_for":0.5,"xg_ag":3,"xg_source":"proxy","inj":0.05},
  "Debrecen": {"league":"NB1","elo":1540,"atk":0.95,"def":1.05,"form":-0.01,"xg_for":1.2,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Diosgyor": {"league":"NB1","elo":1510,"atk":0.85,"def":1.1,"form":-0.03,"xg_for":1.05,"xg_ag":1.45,"inj":0.06,"xg_source":"manual"},
  "Elche": {"elo":1623,"league":"LALIGA","atk_home":0,"atk_away":1.307,"def_home":4.333,"def_away":1.191,"atk":0.654,"def":2.762,"form":-0.08,"xg_for":0.75,"xg_ag":3.51,"xg_source":"proxy","inj":0.05},
  "ES Troyes": {"elo":1600,"league":"LIGUE1","atk_home":0,"atk_away":1.417,"def_home":0,"def_away":0.607,"atk":0.708,"def":0.304,"form":0.06,"xg_for":1,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Espanyol": {"elo":1629,"league":"LALIGA","atk_home":1.176,"atk_away":0.867,"def_home":0.875,"def_away":1.182,"atk":1.022,"def":1.028,"form":-0.04,"xg_for":1.5,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Everton": {"elo":1803,"league":"EPL","atk_home":1.027,"atk_away":0.792,"def_home":0,"def_away":0.514,"atk":0.909,"def":0.257,"form":0.06,"xg_for":1.5,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Ferencvaros": {"league":"NB1","elo":1720,"atk":1.4,"def":0.85,"form":0.05,"xg_for":1.9,"xg_ag":1,"inj":0.05,"xg_source":"manual"},
  "Fiorentina": {"elo":1670,"league":"SERIEA","atk_home":0,"atk_away":0,"def_home":2.286,"def_away":3.048,"atk":0,"def":2.667,"form":-0.12,"xg_for":0,"xg_ag":3.5,"xg_source":"proxy","inj":0.05},
  "Frosinone Calcio": {"elo":1600,"league":"SERIEA","atk_home":0,"atk_away":2.286,"def_home":0.762,"def_away":0,"atk":1.143,"def":0.381,"form":0,"xg_for":1.5,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Fulham": {"elo":1813,"league":"EPL","atk_home":1.027,"atk_away":0,"def_home":2.375,"def_away":0.514,"atk":0.514,"def":1.444,"form":-0.12,"xg_for":1,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Getafe": {"elo":1664,"league":"LALIGA","atk_home":0.591,"atk_away":0,"def_home":0,"def_away":1.773,"atk":0.295,"def":0.886,"form":0,"xg_for":0.5,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Gyor": {"league":"NB1","elo":1540,"atk":0.95,"def":1.05,"form":0,"xg_for":1.2,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Hull City": {"elo":1600,"league":"EPL","atk_home":1.027,"atk_away":0.792,"def_home":0,"def_away":0,"atk":0.909,"def":0,"form":0.12,"xg_for":1.5,"xg_ag":0,"xg_source":"proxy","inj":0.05},
  "Ipswich": {"elo":1640,"league":"EPL","atk_home":1.027,"atk_away":1.583,"def_home":0.792,"def_away":2.568,"atk":1.305,"def":1.68,"form":0,"xg_for":2,"xg_ag":3,"xg_source":"proxy","inj":0.05},
  "Juventus": {"elo":1772,"league":"SERIEA","atk_home":1.524,"atk_away":0.762,"def_home":0,"def_away":0,"atk":1.143,"def":0,"form":0.12,"xg_for":1.5,"xg_ag":0,"xg_source":"proxy","inj":0.05},
  "Kecskemet": {"league":"NB1","elo":1520,"atk":0.9,"def":1.05,"form":-0.01,"xg_for":1.15,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Le Havre": {"elo":1580,"league":"LIGUE1","atk_home":0,"atk_away":0.708,"def_home":0.708,"def_away":0.607,"atk":0.354,"def":0.658,"form":-0.06,"xg_for":0.5,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Le Mans": {"elo":1492,"league":"LIGUE1","atk_home":1.214,"atk_away":1.417,"def_home":1.417,"def_away":1.821,"atk":1.315,"def":1.619,"form":-0.06,"xg_for":2,"xg_ag":2.5,"xg_source":"proxy","inj":0.05},
  "Leeds United": {"elo":1797,"league":"EPL","atk_home":0.514,"atk_away":0.792,"def_home":0.792,"def_away":0,"atk":0.653,"def":0.396,"form":0.06,"xg_for":1,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Levante UD": {"elo":1639,"league":"LALIGA","atk_home":2.955,"atk_away":0,"def_home":1.733,"def_away":0.876,"atk":1.477,"def":1.305,"form":0,"xg_for":2.5,"xg_ag":1.74,"xg_source":"proxy","inj":0.05},
  "Lille OSC": {"elo":1600,"league":"LIGUE1","atk_home":1.214,"atk_away":1.417,"def_home":1.417,"def_away":0,"atk":1.315,"def":0.708,"form":0.06,"xg_for":2,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Liverpool": {"elo":1911,"league":"EPL","atk_home":1.027,"atk_away":1.583,"def_home":1.583,"def_away":1.027,"atk":1.305,"def":1.305,"form":0,"xg_for":2,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Lorient": {"elo":1639,"league":"LIGUE1","atk_home":0.607,"atk_away":0,"def_home":1.417,"def_away":0,"atk":0.304,"def":0.708,"form":-0.06,"xg_for":0.5,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Lyon": {"elo":1732,"league":"LIGUE1","atk_home":0.607,"atk_away":1.417,"def_home":0.708,"def_away":0,"atk":1.012,"def":0.354,"form":0.06,"xg_for":1.5,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Málaga": {"elo":1600,"league":"LALIGA","atk_home":0.591,"atk_away":0,"def_home":0.867,"def_away":1.782,"atk":0.295,"def":1.324,"form":-0.08,"xg_for":0.5,"xg_ag":2.01,"xg_source":"proxy","inj":0.05},
  "Manchester City": {"elo":1600,"league":"EPL","atk_home":1.027,"atk_away":3.167,"def_home":0.792,"def_away":0.514,"atk":2.097,"def":0.653,"form":0.12,"xg_for":3,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Manchester United": {"elo":1600,"league":"EPL","atk_home":2.568,"atk_away":0,"def_home":1.583,"def_away":1.027,"atk":1.284,"def":1.305,"form":0,"xg_for":2.5,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Monza": {"elo":1544,"league":"SERIEA","atk_home":1.524,"atk_away":0.762,"def_home":2.286,"def_away":3.048,"atk":1.143,"def":2.667,"form":-0.12,"xg_for":1.5,"xg_ag":3.5,"xg_source":"proxy","inj":0.05},
  "MTK": {"league":"NB1","elo":1540,"atk":1,"def":1.05,"form":0,"xg_for":1.25,"xg_ag":1.35,"inj":0.05,"xg_source":"manual"},
  "Napoli": {"elo":1780,"league":"SERIEA","atk_home":0.762,"atk_away":1.524,"def_home":1.524,"def_away":0,"atk":1.143,"def":0.762,"form":0,"xg_for":1.5,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Newcastle": {"elo":1838,"league":"EPL","atk_home":1.027,"atk_away":1.583,"def_home":1.583,"def_away":0,"atk":1.305,"def":0.792,"form":0.06,"xg_for":2,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Nice": {"elo":1582,"league":"LIGUE1","atk_home":0,"atk_away":0,"def_home":0,"def_away":1.821,"atk":0,"def":0.911,"form":-0.06,"xg_for":0,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Nottingham Forest": {"elo":1822,"league":"EPL","atk_home":0,"atk_away":1.583,"def_home":0.792,"def_away":1.027,"atk":0.792,"def":0.909,"form":-0.06,"xg_for":1,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Nyiregyhaza": {"league":"NB1","elo":1500,"atk":0.85,"def":1.15,"form":-0.04,"xg_for":1,"xg_ag":1.55,"inj":0.06,"xg_source":"manual"},
  "Osasuna": {"elo":1650,"league":"LALIGA","atk_home":0,"atk_away":1.733,"def_home":0,"def_away":0.591,"atk":0.867,"def":0.295,"form":0.06,"xg_for":1,"xg_ag":0.5,"xg_source":"proxy","inj":0.05},
  "Paks": {"league":"NB1","elo":1600,"atk":1.15,"def":0.95,"form":0.02,"xg_for":1.5,"xg_ag":1.15,"inj":0.05,"xg_source":"manual"},
  "Paris": {"elo":1629,"league":"LIGUE1","atk_home":1.821,"atk_away":0,"def_home":0,"def_away":0,"atk":0.911,"def":0,"form":0.06,"xg_for":1.5,"xg_ag":0,"xg_source":"proxy","inj":0.05},
  "Parma": {"elo":1600,"league":"SERIEA","atk_home":0,"atk_away":0,"def_home":0.762,"def_away":1.524,"atk":0,"def":1.143,"form":-0.12,"xg_for":0,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Puskas Akademia": {"league":"NB1","elo":1620,"atk":1.2,"def":0.95,"form":0.03,"xg_for":1.55,"xg_ag":1.15,"inj":0.05,"xg_source":"manual"},
  "Racing Club de Lens": {"elo":1600,"league":"LIGUE1","atk_home":3.036,"atk_away":0.708,"def_home":1.417,"def_away":1.214,"atk":1.872,"def":1.315,"form":0,"xg_for":3,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Rayo Vallecano": {"elo":1707,"league":"LALIGA","atk_home":0.591,"atk_away":0.867,"def_home":0.867,"def_away":1.182,"atk":0.729,"def":1.024,"form":-0.06,"xg_for":1,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "RC Deportivo La Coruña": {"elo":1600,"league":"LALIGA","atk_home":0.591,"atk_away":0.867,"def_home":0.867,"def_away":0.591,"atk":0.729,"def":0.729,"form":0,"xg_for":1,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Real Betis": {"elo":1747,"league":"LALIGA","atk_home":0.591,"atk_away":1.302,"def_home":0,"def_away":1.486,"atk":0.947,"def":0.743,"form":0.04,"xg_for":1.25,"xg_ag":1.26,"xg_source":"proxy","inj":0.05},
  "Real Madrid": {"elo":1923,"league":"LALIGA","atk_home":2.364,"atk_away":1.733,"def_home":0.431,"def_away":0.591,"atk":2.048,"def":0.511,"form":0.12,"xg_for":3,"xg_ag":0.75,"xg_source":"proxy","inj":0.05},
  "Real Racing Club de Santander": {"elo":1600,"league":"LALIGA","atk_home":1.483,"atk_away":0,"def_home":1.733,"def_away":0.591,"atk":0.741,"def":1.162,"form":0,"xg_for":1.25,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Real Sociedad": {"elo":1669,"league":"LALIGA","atk_home":1.182,"atk_away":0.437,"def_home":0.867,"def_away":1.484,"atk":0.809,"def":1.175,"form":-0.04,"xg_for":1.25,"xg_ag":1.76,"xg_source":"proxy","inj":0.05},
  "Sevilla": {"elo":1626,"league":"LALIGA","atk_home":0.88,"atk_away":2.6,"def_home":1.752,"def_away":0.591,"atk":1.74,"def":1.171,"form":0.04,"xg_for":2.24,"xg_ag":1.51,"xg_source":"proxy","inj":0.05},
  "Strasbourg": {"elo":1711,"league":"LIGUE1","atk_home":1.214,"atk_away":0,"def_home":0.708,"def_away":2.429,"atk":0.607,"def":1.568,"form":0,"xg_for":1,"xg_ag":2.5,"xg_source":"proxy","inj":0.05},
  "Sunderland": {"elo":1736,"league":"EPL","atk_home":0.514,"atk_away":0.792,"def_home":0,"def_away":1.027,"atk":0.653,"def":0.514,"form":0,"xg_for":1,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Torino": {"elo":1624,"league":"SERIEA","atk_home":0.762,"atk_away":0.762,"def_home":1.524,"def_away":1.524,"atk":0.762,"def":1.524,"form":-0.12,"xg_for":1,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Tottenham": {"elo":1777,"league":"EPL","atk_home":0,"atk_away":0,"def_home":1.583,"def_away":1.541,"atk":0,"def":1.562,"form":-0.12,"xg_for":0,"xg_ag":2.5,"xg_source":"proxy","inj":0.05},
  "Toulouse": {"elo":1652,"league":"LIGUE1","atk_home":0,"atk_away":1.417,"def_home":1.417,"def_away":1.214,"atk":0.708,"def":1.315,"form":-0.06,"xg_for":1,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "Udinese": {"elo":1646,"league":"SERIEA","atk_home":0.762,"atk_away":2.286,"def_home":0.762,"def_away":1.524,"atk":1.524,"def":1.143,"form":0.06,"xg_for":2,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Ujpest": {"league":"NB1","elo":1550,"atk":0.95,"def":1,"form":0,"xg_for":1.2,"xg_ag":1.3,"inj":0.05,"xg_source":"manual"},
  "US Sassuolo Calcio": {"elo":1600,"league":"SERIEA","atk_home":1.524,"atk_away":0.762,"def_home":0.762,"def_away":1.524,"atk":1.143,"def":1.143,"form":0,"xg_for":1.5,"xg_ag":1.5,"xg_source":"proxy","inj":0.05},
  "Venezia": {"elo":1599,"league":"SERIEA","atk_home":0,"atk_away":0,"def_home":1.524,"def_away":1.524,"atk":0,"def":1.524,"form":-0.12,"xg_for":0,"xg_ag":2,"xg_source":"proxy","inj":0.05},
  "ZTE": {"league":"NB1","elo":1530,"atk":0.9,"def":1.08,"form":-0.02,"xg_for":1.15,"xg_ag":1.45,"inj":0.05,"xg_source":"manual"},
};

const TEAM_ALIASES = {
  "Man City": "Manchester City",
  "Man Utd": "Manchester United",
  "MU": "Manchester United",
  "Spurs": "Tottenham",
  "Nott'm Forest": "Nottingham Forest",
  "Atleti": "Atletico Madrid",
  "Atletico": "Atletico Madrid",
  "Real": "Real Madrid",
  "Barca": "Barcelona",
  "BVB": "Borussia Dortmund",
  "Gladbach": "Borussia Monchengladbach",
  "Bayern": "Bayern Munich",
  "Leverkusen": "Bayer Leverkusen",
  "PSG": "Paris Saint-Germain",
  "Fradi": "Ferencvaros",
  "FTC": "Ferencvaros"
};
