/* =============================================================
   AUTO-GENERATED by scripts/update-teams.js
   Last run: 2026-05-03T06:10:47.134Z
   Sources:  football-data.org + api.clubelo.com + understat.com
   Schema v2: per-team atk_home/atk_away/def_home/def_away split
              + real xG when xg_source === "understat".
   DO NOT EDIT — this file is overwritten nightly.
   ============================================================= */

const LEAGUE_AVG = {
  "EPL": {
    "home": 1.515,
    "away": 1.227
  },
  "LALIGA": {
    "home": 1.57,
    "away": 1.134
  },
  "SERIEA": {
    "home": 1.291,
    "away": 1.128
  },
  "BUNDES": {
    "home": 1.765,
    "away": 1.463
  },
  "LIGUE1": {
    "home": 1.601,
    "away": 1.224
  },
  "NB1": {
    "home": 1.45,
    "away": 1.15
  },
  "UCL": {
    "home": 1.6,
    "away": 1.3
  },
  "OTHER": {
    "home": 1.5,
    "away": 1.2
  }
};

const TEAMS = {
  "1. FC Köln": {"elo":1600,"league":"BUNDES","atk_home":1.006,"atk_away":0.78,"def_home":1.172,"def_away":1.001,"atk":0.893,"def":1.087,"form":0,"xg_for":1.46,"xg_ag":1.74,"xg_source":"proxy","inj":0.05},
  "AC Milan": {"elo":1781,"league":"SERIEA","atk_home":0.951,"atk_away":1.306,"def_home":0.849,"def_away":0.506,"atk":1.129,"def":0.677,"form":0,"xg_for":1.35,"xg_ag":0.8,"xg_source":"proxy","inj":0.05},
  "Alaves": {"elo":1629,"league":"LALIGA","atk_home":0.885,"atk_away":1.011,"def_home":1.29,"def_away":1.206,"atk":0.948,"def":1.248,"form":-0.024,"xg_for":1.27,"xg_ag":1.68,"xg_source":"proxy","inj":0.05},
  "Angers": {"elo":1550,"league":"LIGUE1","atk_home":0.611,"atk_away":0.504,"def_home":1.02,"def_away":1.032,"atk":0.558,"def":1.026,"form":-0.072,"xg_for":0.8,"xg_ag":1.45,"xg_source":"proxy","inj":0.05},
  "Arsenal": {"elo":2049,"league":"EPL","atk_home":1.418,"atk_away":1.339,"def_home":0.52,"def_away":0.609,"atk":1.379,"def":0.565,"form":0.024,"xg_for":1.9,"xg_ag":0.78,"xg_source":"proxy","inj":0.05},
  "Aston Villa": {"elo":1887,"league":"EPL","atk_home":1.082,"atk_away":0.938,"def_home":0.919,"def_away":0.952,"atk":1.01,"def":0.935,"form":0,"xg_for":1.4,"xg_ag":1.28,"xg_source":"proxy","inj":0.05},
  "Atalanta": {"elo":1772,"league":"SERIEA","atk_home":1.045,"atk_away":1.18,"def_home":0.662,"def_away":0.835,"atk":1.113,"def":0.748,"form":-0.024,"xg_for":1.34,"xg_ag":0.91,"xg_source":"proxy","inj":0.05},
  "Athletic Bilbao": {"elo":1692,"league":"LALIGA","atk_home":0.798,"atk_away":1.067,"def_home":0.992,"def_away":1.205,"atk":0.932,"def":1.099,"form":-0.024,"xg_for":1.23,"xg_ag":1.51,"xg_source":"proxy","inj":0.05},
  "Atletico Madrid": {"elo":1844,"league":"LALIGA","atk_home":1.402,"atk_away":1.07,"def_home":0.881,"def_away":0.824,"atk":1.236,"def":0.852,"form":-0.024,"xg_for":1.71,"xg_ag":1.15,"xg_source":"proxy","inj":0.05},
  "Auxerre": {"elo":1590,"league":"LIGUE1","atk_home":0.531,"atk_away":0.795,"def_home":0.784,"def_away":1.033,"atk":0.663,"def":0.909,"form":0,"xg_for":0.91,"xg_ag":1.31,"xg_source":"proxy","inj":0.05},
  "Barcelona": {"elo":1971,"league":"LALIGA","atk_home":1.92,"atk_away":1.866,"def_home":0.47,"def_away":0.767,"atk":1.893,"def":0.619,"form":0.12,"xg_for":2.57,"xg_ag":0.87,"xg_source":"proxy","inj":0.05},
  "Bayer Leverkusen": {"elo":1813,"league":"BUNDES","atk_home":1.355,"atk_away":1.207,"def_home":0.814,"def_away":0.837,"atk":1.281,"def":0.825,"form":0.072,"xg_for":2.08,"xg_ag":1.33,"xg_source":"proxy","inj":0.05},
  "Bayern Munich": {"elo":2017,"league":"BUNDES","atk_home":2.198,"atk_away":2.27,"def_home":0.856,"def_away":0.635,"atk":2.234,"def":0.745,"form":0.096,"xg_for":3.6,"xg_ag":1.19,"xg_source":"proxy","inj":0.05},
  "Bologna": {"elo":1677,"league":"SERIEA","atk_home":0.666,"atk_away":1.342,"def_home":1.107,"def_away":0.96,"atk":1.004,"def":1.034,"form":-0.024,"xg_for":1.19,"xg_ag":1.24,"xg_source":"proxy","inj":0.05},
  "Borussia Dortmund": {"elo":1839,"league":"BUNDES","atk_home":1.342,"atk_away":1.273,"def_home":0.626,"def_away":0.645,"atk":1.308,"def":0.636,"form":0.024,"xg_for":2.12,"xg_ag":1.03,"xg_source":"proxy","inj":0.05},
  "Borussia Monchengladbach": {"elo":1621,"league":"BUNDES","atk_home":0.744,"atk_away":0.692,"def_home":1.011,"def_away":0.951,"atk":0.718,"def":0.981,"form":-0.024,"xg_for":1.16,"xg_ag":1.58,"xg_source":"proxy","inj":0.05},
  "Bournemouth": {"elo":1848,"league":"EPL","atk_home":0.978,"atk_away":1.273,"def_home":0.976,"def_away":1.169,"atk":1.125,"def":1.073,"form":0.048,"xg_for":1.52,"xg_ag":1.48,"xg_source":"proxy","inj":0.05},
  "Brentford": {"elo":1828,"league":"EPL","atk_home":1.111,"atk_away":1.029,"def_home":0.854,"def_away":1.002,"atk":1.07,"def":0.928,"form":0,"xg_for":1.47,"xg_ag":1.28,"xg_source":"proxy","inj":0.05},
  "Brest": {"elo":1650,"league":"LIGUE1","atk_home":1.126,"atk_away":0.789,"def_home":1.117,"def_away":1.097,"atk":0.958,"def":1.107,"form":-0.072,"xg_for":1.38,"xg_ag":1.56,"xg_source":"proxy","inj":0.05},
  "Brighton": {"elo":1866,"league":"EPL","atk_home":1.038,"atk_away":1.017,"def_home":0.781,"def_away":0.899,"atk":1.027,"def":0.84,"form":0.048,"xg_for":1.41,"xg_ag":1.16,"xg_source":"proxy","inj":0.05},
  "Burnley": {"elo":1665,"league":"EPL","atk_home":0.56,"atk_away":0.881,"def_home":1.3,"def_away":1.64,"atk":0.721,"def":1.47,"form":-0.12,"xg_for":0.96,"xg_ag":2.04,"xg_source":"proxy","inj":0.05},
  "Cagliari": {"elo":1579,"league":"SERIEA","atk_home":0.929,"atk_away":0.819,"def_home":1.02,"def_away":1.39,"atk":0.874,"def":1.205,"form":-0.024,"xg_for":1.06,"xg_ag":1.47,"xg_source":"proxy","inj":0.05},
  "Celta Vigo": {"elo":1685,"league":"LALIGA","atk_home":0.96,"atk_away":1.13,"def_home":1.397,"def_away":0.735,"atk":1.045,"def":1.066,"form":-0.072,"xg_for":1.39,"xg_ag":1.37,"xg_source":"proxy","inj":0.05},
  "Chelsea": {"elo":1841,"league":"EPL","atk_home":0.85,"atk_away":1.365,"def_home":1.059,"def_away":0.989,"atk":1.107,"def":1.024,"form":-0.12,"xg_for":1.48,"xg_ag":1.4,"xg_source":"proxy","inj":0.05},
  "Como": {"elo":1746,"league":"SERIEA","atk_home":1.508,"atk_away":1.33,"def_home":0.799,"def_away":0.575,"atk":1.419,"def":0.687,"form":-0.024,"xg_for":1.72,"xg_ag":0.82,"xg_source":"proxy","inj":0.05},
  "Crystal Palace": {"elo":1810,"league":"EPL","atk_home":0.602,"atk_away":1.019,"def_home":0.892,"def_away":0.893,"atk":0.81,"def":0.893,"form":0.024,"xg_for":1.08,"xg_ag":1.22,"xg_source":"proxy","inj":0.05},
  "Debrecen": {"league":"NB1","elo":1540,"atk":0.95,"def":1.05,"form":-0.01,"xg_for":1.2,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Diosgyor": {"league":"NB1","elo":1510,"atk":0.85,"def":1.1,"form":-0.03,"xg_for":1.05,"xg_ag":1.45,"inj":0.06,"xg_source":"manual"},
  "Eintracht Frankfurt": {"elo":1678,"league":"BUNDES","atk_home":0.921,"atk_away":1.194,"def_home":1.072,"def_away":1.177,"atk":1.058,"def":1.125,"form":-0.024,"xg_for":1.69,"xg_ag":1.82,"xg_source":"proxy","inj":0.05},
  "Elche": {"elo":1624,"league":"LALIGA","atk_home":1.072,"atk_away":0.89,"def_home":0.993,"def_away":1.287,"atk":0.981,"def":1.14,"form":0.072,"xg_for":1.35,"xg_ag":1.57,"xg_source":"proxy","inj":0.05},
  "Espanyol": {"elo":1616,"league":"LALIGA","atk_home":0.66,"atk_away":0.966,"def_home":1.158,"def_away":1.111,"atk":0.813,"def":1.134,"form":-0.072,"xg_for":1.07,"xg_ag":1.53,"xg_source":"proxy","inj":0.05},
  "Everton": {"elo":1821,"league":"EPL","atk_home":0.867,"atk_away":0.94,"def_home":1.023,"def_away":0.798,"atk":0.904,"def":0.91,"form":-0.048,"xg_for":1.23,"xg_ag":1.23,"xg_source":"proxy","inj":0.05},
  "FC Augsburg": {"elo":1631,"league":"BUNDES","atk_home":0.794,"atk_away":0.873,"def_home":1.108,"def_away":1.003,"atk":0.834,"def":1.056,"form":0.048,"xg_for":1.34,"xg_ag":1.7,"xg_source":"proxy","inj":0.05},
  "FC Heidenheim": {"elo":1539,"league":"BUNDES","atk_home":0.879,"atk_away":0.696,"def_home":1.484,"def_away":1.189,"atk":0.788,"def":1.336,"form":0.024,"xg_for":1.29,"xg_ag":2.13,"xg_source":"proxy","inj":0.05},
  "Ferencvaros": {"league":"NB1","elo":1720,"atk":1.4,"def":0.85,"form":0.05,"xg_for":1.9,"xg_ag":1,"inj":0.05,"xg_source":"manual"},
  "Fiorentina": {"elo":1661,"league":"SERIEA","atk_home":0.879,"atk_away":1.015,"def_home":0.924,"def_away":1.133,"atk":0.947,"def":1.028,"form":0.048,"xg_for":1.14,"xg_ag":1.25,"xg_source":"proxy","inj":0.05},
  "Fulham": {"elo":1812,"league":"EPL","atk_home":1.082,"atk_away":0.685,"def_home":0.907,"def_away":1.074,"atk":0.884,"def":0.99,"form":0,"xg_for":1.24,"xg_ag":1.37,"xg_source":"proxy","inj":0.05},
  "Genoa": {"elo":1626,"league":"SERIEA","atk_home":0.972,"atk_away":0.942,"def_home":1.203,"def_away":1.035,"atk":0.957,"def":1.119,"form":0,"xg_for":1.16,"xg_ag":1.35,"xg_source":"proxy","inj":0.05},
  "Getafe": {"elo":1670,"league":"LALIGA","atk_home":0.552,"atk_away":0.722,"def_home":0.726,"def_away":0.722,"atk":0.637,"def":0.724,"form":0.024,"xg_for":0.84,"xg_ag":0.98,"xg_source":"proxy","inj":0.05},
  "Girona": {"elo":1647,"league":"LALIGA","atk_home":0.744,"atk_away":0.892,"def_home":1.222,"def_away":0.923,"atk":0.818,"def":1.072,"form":-0.048,"xg_for":1.09,"xg_ag":1.42,"xg_source":"proxy","inj":0.05},
  "Gyor": {"league":"NB1","elo":1540,"atk":0.95,"def":1.05,"form":0,"xg_for":1.2,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Hamburger SV": {"elo":1575,"league":"BUNDES","atk_home":0.755,"atk_away":0.666,"def_home":0.878,"def_away":1.104,"atk":0.711,"def":0.991,"form":-0.048,"xg_for":1.15,"xg_ag":1.62,"xg_source":"proxy","inj":0.05},
  "Hellas Verona": {"elo":1494,"league":"SERIEA","atk_home":0.559,"atk_away":0.597,"def_home":1.291,"def_away":1.412,"atk":0.578,"def":1.352,"form":-0.072,"xg_for":0.7,"xg_ag":1.64,"xg_source":"proxy","inj":0.05},
  "Hoffenheim": {"elo":1715,"league":"BUNDES","atk_home":1.212,"atk_away":1.262,"def_home":0.876,"def_away":1.017,"atk":1.237,"def":0.947,"form":0.024,"xg_for":1.99,"xg_ag":1.54,"xg_source":"proxy","inj":0.05},
  "Inter": {"elo":1890,"league":"SERIEA","atk_home":2.162,"atk_away":1.744,"def_home":0.801,"def_away":0.731,"atk":1.953,"def":0.766,"form":0.072,"xg_for":2.38,"xg_ag":0.92,"xg_source":"proxy","inj":0.05},
  "Juventus": {"elo":1797,"league":"SERIEA","atk_home":1.562,"atk_away":1.228,"def_home":0.647,"def_away":0.718,"atk":1.395,"def":0.683,"form":0.072,"xg_for":1.7,"xg_ag":0.83,"xg_source":"proxy","inj":0.05},
  "Kecskemet": {"league":"NB1","elo":1520,"atk":0.9,"def":1.05,"form":-0.01,"xg_for":1.15,"xg_ag":1.4,"inj":0.05,"xg_source":"manual"},
  "Lazio": {"elo":1712,"league":"SERIEA","atk_home":1.122,"atk_away":0.663,"def_home":1.16,"def_away":0.53,"atk":0.893,"def":0.845,"form":0.024,"xg_for":1.1,"xg_ag":1,"xg_source":"proxy","inj":0.05},
  "Le Havre": {"elo":1564,"league":"LIGUE1","atk_home":0.794,"atk_away":0.514,"def_home":0.9,"def_away":1.026,"atk":0.654,"def":0.963,"form":-0.024,"xg_for":0.95,"xg_ag":1.37,"xg_source":"proxy","inj":0.05},
  "Lecce": {"elo":1543,"league":"SERIEA","atk_home":0.557,"atk_away":0.59,"def_home":1.221,"def_away":1.069,"atk":0.573,"def":1.145,"form":-0.048,"xg_for":0.69,"xg_ag":1.38,"xg_source":"proxy","inj":0.05},
  "Leeds United": {"elo":1793,"league":"EPL","atk_home":1.045,"atk_away":0.962,"def_home":0.927,"def_away":1.131,"atk":1.003,"def":1.029,"form":0.072,"xg_for":1.38,"xg_ag":1.43,"xg_source":"proxy","inj":0.05},
  "Levante UD": {"elo":1618,"league":"LALIGA","atk_home":0.812,"atk_away":0.811,"def_home":1.187,"def_away":1.161,"atk":0.811,"def":1.174,"form":0,"xg_for":1.1,"xg_ag":1.58,"xg_source":"proxy","inj":0.05},
  "Lille OSC": {"elo":1600,"league":"LIGUE1","atk_home":0.921,"atk_away":1.324,"def_home":0.75,"def_away":0.69,"atk":1.122,"def":0.72,"form":0.096,"xg_for":1.55,"xg_ag":1.01,"xg_source":"proxy","inj":0.05},
  "Liverpool": {"elo":1933,"league":"EPL","atk_home":1.277,"atk_away":1.182,"def_home":0.85,"def_away":0.98,"atk":1.23,"def":0.915,"form":0.048,"xg_for":1.69,"xg_ag":1.26,"xg_source":"proxy","inj":0.05},
  "Lorient": {"elo":1637,"league":"LIGUE1","atk_home":1.179,"atk_away":0.738,"def_home":1.1,"def_away":0.999,"atk":0.959,"def":1.05,"form":-0.024,"xg_for":1.4,"xg_ag":1.47,"xg_source":"proxy","inj":0.05},
  "Lyon": {"elo":1751,"league":"LIGUE1","atk_home":1.093,"atk_away":1.13,"def_home":0.686,"def_away":0.768,"atk":1.112,"def":0.727,"form":0.048,"xg_for":1.57,"xg_ag":1.03,"xg_source":"proxy","inj":0.05},
  "Mainz": {"elo":1674,"league":"BUNDES","atk_home":0.77,"atk_away":0.871,"def_home":0.958,"def_away":0.979,"atk":0.821,"def":0.968,"form":0,"xg_for":1.32,"xg_ag":1.56,"xg_source":"proxy","inj":0.05},
  "Mallorca": {"elo":1640,"league":"LALIGA","atk_home":1.068,"atk_away":0.761,"def_home":1.009,"def_away":1.144,"atk":0.915,"def":1.077,"form":0.048,"xg_for":1.27,"xg_ag":1.47,"xg_source":"proxy","inj":0.05},
  "Manchester City": {"elo":1600,"league":"EPL","atk_home":1.544,"atk_away":1.327,"def_home":0.621,"def_away":0.627,"atk":1.435,"def":0.624,"form":0.072,"xg_for":1.98,"xg_ag":0.86,"xg_source":"proxy","inj":0.05},
  "Manchester United": {"elo":1600,"league":"EPL","atk_home":1.289,"atk_away":1.299,"def_home":0.955,"def_away":0.961,"atk":1.294,"def":0.958,"form":0.048,"xg_for":1.77,"xg_ag":1.31,"xg_source":"proxy","inj":0.05},
  "Marseille": {"elo":1722,"league":"LIGUE1","atk_home":1.384,"atk_away":1.006,"def_home":0.985,"def_away":1.065,"atk":1.195,"def":1.025,"form":-0.048,"xg_for":1.72,"xg_ag":1.46,"xg_source":"proxy","inj":0.05},
  "Metz": {"elo":1501,"league":"LIGUE1","atk_home":0.604,"atk_away":0.876,"def_home":1.513,"def_away":1.66,"atk":0.74,"def":1.586,"form":-0.072,"xg_for":1.02,"xg_ag":2.26,"xg_source":"proxy","inj":0.05},
  "Monaco": {"elo":1731,"league":"LIGUE1","atk_home":1.273,"atk_away":1.219,"def_home":1.077,"def_away":1.01,"atk":1.246,"def":1.043,"form":0.024,"xg_for":1.77,"xg_ag":1.47,"xg_source":"proxy","inj":0.05},
  "MTK": {"league":"NB1","elo":1540,"atk":1,"def":1.05,"form":0,"xg_for":1.25,"xg_ag":1.35,"inj":0.05,"xg_source":"manual"},
  "Nantes": {"elo":1525,"league":"LIGUE1","atk_home":0.744,"atk_away":0.529,"def_home":1.331,"def_away":0.95,"atk":0.636,"def":1.14,"form":-0.024,"xg_for":0.92,"xg_ag":1.58,"xg_source":"proxy","inj":0.05},
  "Napoli": {"elo":1783,"league":"SERIEA","atk_home":1.359,"atk_away":1.056,"def_home":0.782,"def_away":0.773,"atk":1.207,"def":0.778,"form":0.024,"xg_for":1.47,"xg_ag":0.94,"xg_source":"proxy","inj":0.05},
  "Newcastle": {"elo":1826,"league":"EPL","atk_home":1.219,"atk_away":0.784,"def_home":1.349,"def_away":0.88,"atk":1.001,"def":1.114,"form":-0.072,"xg_for":1.4,"xg_ag":1.49,"xg_source":"proxy","inj":0.05},
  "Nice": {"elo":1590,"league":"LIGUE1","atk_home":0.703,"atk_away":0.844,"def_home":1.462,"def_away":1.133,"atk":0.774,"def":1.298,"form":-0.024,"xg_for":1.08,"xg_ag":1.8,"xg_source":"proxy","inj":0.05},
  "Nottingham Forest": {"elo":1829,"league":"EPL","atk_home":0.706,"atk_away":1.256,"def_home":0.928,"def_away":0.896,"atk":0.981,"def":0.912,"form":0.072,"xg_for":1.3,"xg_ag":1.25,"xg_source":"proxy","inj":0.05},
  "Nyiregyhaza": {"league":"NB1","elo":1500,"atk":0.85,"def":1.15,"form":-0.04,"xg_for":1,"xg_ag":1.55,"inj":0.06,"xg_source":"manual"},
  "Osasuna": {"elo":1683,"league":"LALIGA","atk_home":1.079,"atk_away":0.628,"def_home":1.065,"def_away":0.834,"atk":0.853,"def":0.95,"form":-0.024,"xg_for":1.2,"xg_ag":1.26,"xg_source":"proxy","inj":0.05},
  "Paks": {"league":"NB1","elo":1600,"atk":1.15,"def":0.95,"form":0.02,"xg_for":1.5,"xg_ag":1.15,"inj":0.05,"xg_source":"manual"},
  "Paris": {"elo":1603,"league":"LIGUE1","atk_home":0.906,"atk_away":0.928,"def_home":1.382,"def_away":0.745,"atk":0.917,"def":1.064,"form":0.048,"xg_for":1.29,"xg_ag":1.44,"xg_source":"proxy","inj":0.05},
  "Paris Saint-Germain": {"elo":1600,"league":"LIGUE1","atk_home":1.573,"atk_away":1.655,"def_home":0.686,"def_away":0.583,"atk":1.614,"def":0.634,"form":0.048,"xg_for":2.27,"xg_ag":0.89,"xg_source":"proxy","inj":0.05},
  "Parma": {"elo":1603,"league":"SERIEA","atk_home":0.592,"atk_away":0.662,"def_home":1.133,"def_away":0.809,"atk":0.627,"def":0.971,"form":0.024,"xg_for":0.76,"xg_ag":1.16,"xg_source":"proxy","inj":0.05},
  "Pisa": {"elo":1480,"league":"SERIEA","atk_home":0.451,"atk_away":0.738,"def_home":1.217,"def_away":1.85,"atk":0.595,"def":1.534,"form":-0.12,"xg_for":0.71,"xg_ag":1.88,"xg_source":"proxy","inj":0.05},
  "Puskas Akademia": {"league":"NB1","elo":1620,"atk":1.2,"def":0.95,"form":0.03,"xg_for":1.55,"xg_ag":1.15,"inj":0.05,"xg_source":"manual"},
  "Racing Club de Lens": {"elo":1600,"league":"LIGUE1","atk_home":1.48,"atk_away":1.4,"def_home":0.646,"def_away":0.912,"atk":1.44,"def":0.779,"form":0.024,"xg_for":2.04,"xg_ag":1.13,"xg_source":"proxy","inj":0.05},
  "Rayo Vallecano": {"elo":1667,"league":"LALIGA","atk_home":0.852,"atk_away":0.589,"def_home":0.746,"def_away":1.102,"atk":0.72,"def":0.924,"form":0,"xg_for":1,"xg_ag":1.29,"xg_source":"proxy","inj":0.05},
  "RB Leipzig": {"elo":1785,"league":"BUNDES","atk_home":1.339,"atk_away":1.095,"def_home":0.823,"def_away":0.811,"atk":1.217,"def":0.817,"form":0.072,"xg_for":1.98,"xg_ag":1.32,"xg_source":"proxy","inj":0.05},
  "Real Betis": {"elo":1736,"league":"LALIGA","atk_home":1.034,"atk_away":1.139,"def_home":0.927,"def_away":0.92,"atk":1.087,"def":0.923,"form":0,"xg_for":1.46,"xg_ag":1.25,"xg_source":"proxy","inj":0.05},
  "Real Madrid": {"elo":1916,"league":"LALIGA","atk_home":1.468,"atk_away":1.523,"def_home":0.776,"def_away":0.675,"atk":1.495,"def":0.726,"form":0.024,"xg_for":2.02,"xg_ag":0.97,"xg_source":"proxy","inj":0.05},
  "Real Oviedo": {"elo":1600,"league":"LALIGA","atk_home":0.375,"atk_away":1.03,"def_home":0.83,"def_away":1.373,"atk":0.702,"def":1.101,"form":0,"xg_for":0.88,"xg_ag":1.55,"xg_source":"proxy","inj":0.05},
  "Real Sociedad": {"elo":1685,"league":"LALIGA","atk_home":1.238,"atk_away":1.177,"def_home":1.291,"def_away":1.136,"atk":1.207,"def":1.213,"form":-0.024,"xg_for":1.64,"xg_ag":1.62,"xg_source":"proxy","inj":0.05},
  "Rennes": {"elo":1732,"league":"LIGUE1","atk_home":1.059,"atk_away":1.56,"def_home":0.82,"def_away":1.037,"atk":1.31,"def":0.928,"form":0.096,"xg_for":1.8,"xg_ag":1.33,"xg_source":"proxy","inj":0.05},
  "Roma": {"elo":1769,"league":"SERIEA","atk_home":1.3,"atk_away":1.126,"def_home":0.534,"def_away":0.963,"atk":1.213,"def":0.749,"form":0.048,"xg_for":1.47,"xg_ag":0.92,"xg_source":"proxy","inj":0.05},
  "SC Freiburg": {"elo":1721,"league":"BUNDES","atk_home":1.05,"atk_away":0.653,"def_home":0.917,"def_away":1.137,"atk":0.851,"def":1.027,"form":0.024,"xg_for":1.4,"xg_ag":1.67,"xg_source":"proxy","inj":0.05},
  "Sevilla": {"elo":1605,"league":"LALIGA","atk_home":0.803,"atk_away":0.936,"def_home":1.227,"def_away":1.245,"atk":0.869,"def":1.236,"form":-0.072,"xg_for":1.16,"xg_ag":1.67,"xg_source":"proxy","inj":0.05},
  "St. Pauli": {"elo":1554,"league":"BUNDES","atk_home":0.535,"atk_away":0.458,"def_home":1.157,"def_away":0.976,"atk":0.496,"def":1.067,"form":-0.072,"xg_for":0.81,"xg_ag":1.71,"xg_source":"proxy","inj":0.05},
  "Strasbourg": {"elo":1725,"league":"LIGUE1","atk_home":0.961,"atk_away":1.402,"def_home":0.788,"def_away":1.057,"atk":1.182,"def":0.923,"form":0.048,"xg_for":1.63,"xg_ag":1.33,"xg_source":"proxy","inj":0.05},
  "Sunderland": {"elo":1700,"league":"EPL","atk_home":0.815,"atk_away":0.715,"def_home":1.001,"def_away":1.033,"atk":0.765,"def":1.017,"form":0,"xg_for":1.06,"xg_ag":1.4,"xg_source":"proxy","inj":0.05},
  "Torino": {"elo":1631,"league":"SERIEA","atk_home":1.126,"atk_away":0.766,"def_home":1.333,"def_away":1.413,"atk":0.946,"def":1.373,"form":0,"xg_for":1.16,"xg_ag":1.66,"xg_source":"proxy","inj":0.05},
  "Tottenham": {"elo":1759,"league":"EPL","atk_home":0.77,"atk_away":1.001,"def_home":1.55,"def_away":0.896,"atk":0.885,"def":1.223,"form":-0.024,"xg_for":1.2,"xg_ag":1.63,"xg_source":"proxy","inj":0.05},
  "Toulouse": {"elo":1634,"league":"LIGUE1","atk_home":0.83,"atk_away":1.14,"def_home":1.17,"def_away":0.959,"atk":0.985,"def":1.064,"form":-0.048,"xg_for":1.36,"xg_ag":1.48,"xg_source":"proxy","inj":0.05},
  "Udinese": {"elo":1643,"league":"SERIEA","atk_home":0.769,"atk_away":1.391,"def_home":0.902,"def_away":1.172,"atk":1.08,"def":1.037,"form":0.024,"xg_for":1.28,"xg_ag":1.27,"xg_source":"proxy","inj":0.05},
  "Ujpest": {"league":"NB1","elo":1550,"atk":0.95,"def":1,"form":0,"xg_for":1.2,"xg_ag":1.3,"inj":0.05,"xg_source":"manual"},
  "Union Berlin": {"elo":1589,"league":"BUNDES","atk_home":0.76,"atk_away":0.627,"def_home":1.139,"def_away":1.119,"atk":0.693,"def":1.129,"form":-0.072,"xg_for":1.13,"xg_ag":1.82,"xg_source":"proxy","inj":0.05},
  "US Cremonese": {"elo":1600,"league":"SERIEA","atk_home":0.636,"atk_away":0.595,"def_home":1.294,"def_away":1.27,"atk":0.616,"def":1.282,"form":-0.024,"xg_for":0.75,"xg_ag":1.55,"xg_source":"proxy","inj":0.05},
  "US Sassuolo Calcio": {"elo":1600,"league":"SERIEA","atk_home":0.984,"atk_away":1.007,"def_home":1.196,"def_away":0.944,"atk":0.995,"def":1.07,"form":0.024,"xg_for":1.2,"xg_ag":1.28,"xg_source":"proxy","inj":0.05},
  "Valencia": {"elo":1665,"league":"LALIGA","atk_home":0.862,"atk_away":0.754,"def_home":1.169,"def_away":0.993,"atk":0.808,"def":1.081,"form":-0.048,"xg_for":1.1,"xg_ag":1.44,"xg_source":"proxy","inj":0.05},
  "VfB Stuttgart": {"elo":1754,"league":"BUNDES","atk_home":0.978,"atk_away":1.741,"def_home":0.637,"def_away":1.147,"atk":1.359,"def":0.892,"form":-0.024,"xg_for":2.14,"xg_ag":1.48,"xg_source":"proxy","inj":0.05},
  "Villarreal": {"elo":1760,"league":"LALIGA","atk_home":1.564,"atk_away":1.164,"def_home":0.829,"def_away":0.899,"atk":1.364,"def":0.864,"form":0.048,"xg_for":1.89,"xg_ag":1.18,"xg_source":"proxy","inj":0.05},
  "Werder Bremen": {"elo":1600,"league":"BUNDES","atk_home":0.673,"atk_away":0.756,"def_home":1.251,"def_away":0.945,"atk":0.714,"def":1.098,"form":-0.048,"xg_for":1.15,"xg_ag":1.75,"xg_source":"proxy","inj":0.05},
  "West Ham": {"elo":1770,"league":"EPL","atk_home":0.987,"atk_away":0.78,"def_home":1.242,"def_away":1.185,"atk":0.884,"def":1.214,"form":0,"xg_for":1.23,"xg_ag":1.66,"xg_source":"proxy","inj":0.05},
  "Wolfsburg": {"elo":1585,"league":"BUNDES","atk_home":0.708,"atk_away":0.926,"def_home":1.274,"def_away":1.398,"atk":0.817,"def":1.336,"form":-0.048,"xg_for":1.3,"xg_ag":2.17,"xg_source":"proxy","inj":0.05},
  "Wolves": {"elo":1678,"league":"EPL","atk_home":0.663,"atk_away":0.348,"def_home":1.374,"def_away":1.213,"atk":0.506,"def":1.293,"form":-0.072,"xg_for":0.72,"xg_ag":1.76,"xg_source":"proxy","inj":0.05},
  "ZTE": {"league":"NB1","elo":1530,"atk":0.9,"def":1.08,"form":-0.02,"xg_for":1.15,"xg_ag":1.45,"inj":0.05,"xg_source":"manual"},
};

const TEAM_ALIASES = {
  "Man City": "Manchester City",
  "Man Utd": "Manchester United",
  "MU": "Manchester United",
  "Spurs": "Tottenham",
  "Nott'm Forest": "Nottingham Forest",
  "Atleti": "Atletico Madrid",
  "Atletico": "Atletico Madrid",
  "Real": "Real Madrid",
  "Barca": "Barcelona",
  "BVB": "Borussia Dortmund",
  "Gladbach": "Borussia Monchengladbach",
  "Bayern": "Bayern Munich",
  "Leverkusen": "Bayer Leverkusen",
  "PSG": "Paris Saint-Germain",
  "Fradi": "Ferencvaros",
  "FTC": "Ferencvaros"
};
